### ISSUE TITLE
Tidy Up Badges!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aguid#16]
This does not look great:
![image](https://user-images.githubusercontent.com/194400/76036433-fd8ff280-5f3b-11ea-9474-7096028cab4f.png)

# Todo

+ [ ] Update dependencies where necessary
+ [ ] Tidy up the badges 
+ [ ] Publish new version (patch) of module
